name: Update Tools

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Chocolatey
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          curl -fsSL https://packages.chocolatey.org/chocolatey.list | sudo tee /etc/apt/sources.list.d/chocolatey.list
          sudo apt-get update
          sudo apt-get install -y chocolatey

      - name: Update tools.json
        run: |
          choco outdated --limit-output | while read -r line; do
            tool=$(echo $line | cut -d'|' -f1)
            version=$(echo $line | cut -d'|' -f3)
            jq --arg tool "$tool" --arg version "$version" '.tools[$tool] = $version' tools.json > tools.tmp.json
            mv tools.tmp.json tools.json
          done

      - name: Create new branch and commit changes
        run: |
          BRANCH_NAME="feature/$(date +'%m_%Y')_tools_version_update"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -B $BRANCH_NAME
          git add tools.json
          git commit -m 'Update tools.json with latest versions'
          git push -u origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update tools.json with latest versions'
          branch: ${{ steps.create_branch.outputs.branch }}
          title: 'Update tools.json with latest versions'
          body: 'This PR updates the tools.json file with the latest versions of the tools from Chocolatey.'
          labels: 'automated update'
          assignees: 'atleyvirdee'