name: Update Tools

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-tools:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update tools.json
        run: |
          const fs = require('fs');
          const https = require('https');

          const tools = JSON.parse(fs.readFileSync('tools.json', 'utf8'));
          const toolNames = Object.keys(tools.tools);

          toolNames.forEach(tool => {
            https.get(`https://community.chocolatey.org/api/v2/package/${tool}`, (resp) => {
              let data = '';

              resp.on('data', (chunk) => {
                data += chunk;
              });

              resp.on('end', () => {
                const latestVersion = JSON.parse(data).Properties.version;
                tools.tools[tool] = latestVersion;

                fs.writeFileSync('tools.json', JSON.stringify(tools, null, 2));
              });
            }).on('error', (err) => {
              console.log('Error: ' + err.message);
            });
          });
        shell: node

      - name: Create new branch and commit changes
        run: |
          $branchName = "feature/$(Get-Date -Format 'MM_yyyy')_tools_version_update"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -B $branchName
          git add tools.json
          git commit -m 'Update tools.json with latest versions'
          git push -u origin $branchName
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update tools.json with latest versions'
          branch: ${{ steps.create_branch.outputs.branch }}
          title: 'Update tools.json with latest versions'
          body: 'This PR updates the tools.json file with the latest versions of the tools from Chocolatey.'
          labels: 'automated update'
          assignees: 'atleyvirdee'