name: Update Tools

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-tools:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PowerShell
        uses: actions/setup-powershell@v1

      - name: Update tools.json
        run: |
          $tools = Get-Content -Raw -Path "tools.json" | ConvertFrom-Json
          foreach ($tool in $tools.tools.PSObject.Properties.Name) {
            $latestVersion = (Invoke-RestMethod -Uri "https://community.chocolatey.org/api/v2/package/$tool" -Method Get -Headers @{"Accept"="application/json"}).Properties.version
            $tools.tools.$tool = $latestVersion
          }
          $tools | ConvertTo-Json -Depth 32 | Set-Content -Path "tools.json"
        shell: pwsh

      - name: Create new branch and commit changes
        run: |
          $branchName = "feature/$(Get-Date -Format 'MM_yyyy')_tools_version_update"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -B $branchName
          git add tools.json
          git commit -m 'Update tools.json with latest versions'
          git push -u origin $branchName
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update tools.json with latest versions'
          branch: ${{ steps.create_branch.outputs.branch }}
          title: 'Update tools.json with latest versions'
          body: 'This PR updates the tools.json file with the latest versions of the tools from Chocolatey.'
          labels: 'automated update'
          assignees: 'atleyvirdee'